### ISSUE TITLE
New release to have fixed doc links

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-time#24]
Hello @tmeckel,

Can you create a new release of this provider? For the SEO on our website, we had to remove some broken links, one of them being for this `time` provider:

https://github.com/pulumi/registry/pull/2322/files#diff-51d9b356a4353a5991053ed4b737cf5d60854ee538111510da2d551a1e980e79

The link is [already in this repo](https://github.com/pulumiverse/pulumi-time/commit/1f8b701dbe495e654d9fdafc78f78a343e512e18), but not released yet.

**Comment by tmeckel** [comment]
@ringods any special requirements? Or simply create a new version tag `v0.0.10`, which will fire of the GitHub workflow.

**Comment by ringods** [comment]
No special requirements. Triggering the release would be enough.

**Comment by tmeckel** [comment]
Closed by #28
