### ISSUE TITLE
Proper tagging for `pulumi plugin install` to work correctly in Golang.

### ISSUE THREAD

**Issue by vboulineau** [pulumiverse/pulumi-time#52]
Hello,

Currently this repository is only tagged with `vX.Y.Z` version and not `sdk/vX.Y.Z` version.
However we imported in Golang, the plugin is imported as `github.com/pulumiverse/pulumi-time/sdk`, triggering calls to

https://proxy.golang.org/github.com/pulumiverse/pulumi-time/sdk/@v/v0.16.0.info, which replies with:
```
not found: github.com/pulumiverse/pulumi-time/sdk@v0.16.0: invalid version: unknown revision sdk/v0.16.0
```

It ends up by imported in `go.mod` with:
```
	github.com/pulumiverse/pulumi-time/sdk v0.0.0-20231010123146-089d7304da13
```

Which is not parsable by `pulumi plugin install` command, and thus, is ignored:
```
I0320 14:09:56.283042   11023 sink.go:170] defaultSink::Infoerr(I0320 14:09:56.283024   11026 main.go:688] GetRequiredPlugins: Ignoring dependency: github.com/pulumiverse/pulumi-time/sdk, version: v0.0.0-20231010123146-089d7304da13, error: invalid pseduoversion with no prior tag
)
I0320 14:09:56.283024   11026 main.go:688] GetRequiredPlugins: Ignoring dependency: github.com/pulumiverse/pulumi-time/sdk, version: v0.0.0-20231010123146-089d7304da13, error: invalid pseduoversion with no prior tag
```

Could please duplicate `vX.Y.Z` tags to `sdk/vX.Y.Z` so that this pluign can be cleanly imported and downloaded automatically by Pulumi in Go?

(Example: https://github.com/pulumi/pulumi-libvirt)

**Comment by tmeckel** [comment]
@vboulineau created SDK tags
