### ISSUE TITLE
None of the resources are doing anything

### ISSUE THREAD

**Issue by abjrcode** [pulumiverse/pulumi-time#59]
Just the base example:

```
new time.Rotating('rot', {
    rotationMinutes: 1,
})
```

Running `pulumi up` creates the resource as expected but after `1` minute (as configured) nothing is updated. It never seems to see that the time is past the base/creation timestamp.

I tried the same with Terraform and the exact minimal setup and it works

Plugin Version: `0.0.17`
Pulumi Version: `3.130.0`

**Comment by tmeckel** [comment]
You need to add `--refresh` to `pulumi up`
